### ISSUE TITLE
各種データの入力方法の整備

### ISSUE THREAD

**Issue by pocka** [coop-mojo/moecoop#14]
現状だとレシピ情報なんかはJSON手打ちだと思うので、何らかの入力フォームを用意したほうがいいと思います。

GUIじゃなくても、CLIを配備したり、推奨するJSON編集環境を記載するなどすれば、JSONの仕様を知らなくても気軽に参加できてよいかと。

個人的にはケツカンマやクォート忘れで日常的にJSONパーサに怒られてるので入力フォームがあったほうが嬉しいです:sweat:

**Comment by coop-mojo** [comment]
確かに手打ち以外の方法があったほうがいいですね．
何かいい方法を考えてみます．

**Comment by coop-mojo** [comment]
最新版で，アイテムの基本的な情報に関しては知恵袋内で入力できるようにしてみました．
単品ならこの方法でもいいと思うのですが，いかがでしょう？

**Comment by pocka** [comment]
ありがとうございます。これなら簡単に出来ていいですね

PR上げるときは更新した行をresourceにある該当のJSONファイルに追加して送ればいいのかな？

**Comment by coop-mojo** [comment]
そうですね． `userdata/wisdom` 以下にあるファイルは全て `resource` 以下にある JSON ファイルと構造が同じなので，追加していただければオーケーです！

**Comment by pocka** [comment]
了解です、対応ありがとうございました :smile:
