### ISSUE TITLE
レシピ材料画面で特定の操作を行うとアプリケーションがクラッシュする

### ISSUE THREAD

**Issue by pocka** [coop-mojo/moecoop#20]
# 概要

レシピ材料画面で以下の操作を行った際にAPPCRASHが発生する。
## Aパターン(Twitterでの報告があったもの)
1. 文字列を入力し、作成候補をチェック
2. 入力内容を変更し別の候補にもチェック
3. 最初のチェックを外すと発生
## Bパターン
1. 文字列を入力し、作成候補を複数チェックしているとで発生(大丈夫なパターンとダメなパターンがある模様)

> 例えば、 `か`と入力し、`カオス かけそば`をチェック。その後`かぼちゃコロッケ`にチェックを入れようとすると必ずクラッシュする。
# 環境

version 0.3.1 and 0.3.2
OS: Windows8.1 (x64)

Linux環境では発生せず。
# 例外コード

`c0000096`

**Comment by coop-mojo** [comment]
パターンA は Windows 10 64bit 版では再現できないですね…
パターンB は Windows 10 環境で再現できました！

**Comment by coop-mojo** [comment]
原因が分かりました！
今週末は用事があって修正できないため、修正版の公開は週明けになりそうです。

**Comment by coop-mojo** [comment]
修正しました！
生焼け版では直っているはずです―。

**Comment by coop-mojo** [comment]
一旦クローズしますね―。
直ってなかったら reopen してくださいな！
